### ISSUE TITLE
Update the icon library (font-awesome) in the admin UI to match the current version used on the frontend

### ISSUE THREAD

**Issue by AyupMike** [RoyalBoroughKingston/ck-api#120]
**Describe the bug**
FontAwesome 4.x is being used in the admin UI which is a mismatch to the version used on the front-end which is [5.x](https://fontawesome.com).

This means some of the icon names have changed so icons are not rendering on the front-end properly.

**To Reproduce**
1. Visit: https://connectedkingston.uk
2. Look at the `Money` category on the homepage - no icon is found for `fa-gbp` as it's been renamed to `fa-pound-sign`

**Expected behavior**
All fonts to render correctly on the front-end

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**

**Comment by matthew-inamdar** [comment]
This is to be fixed on the backend. Closing as tracking here: https://github.com/RoyalBoroughKingston/ck-backend/issues/26
