### ISSUE TITLE
Branding update

### ISSUE THREAD

**Issue by BforBen** [RoyalBoroughKingston/ck-api#166]
I've made some changes for the branding in the `ck-branding` branch. I wasn't sure where to upload the image to and what the path would be in `layout.blade.php`. Otherwise I think it's done.

![ck-logo-horizontal-white](https://user-images.githubusercontent.com/426361/50344506-3902f480-0523-11e9-8ce3-2dbd91923f60.png)

**Comment by BforBen** [comment]
There is an image in the whitespace below my message! It's ck-logo-horizontal-white.

**Comment by matthew-inamdar** [comment]
We'll need to replicate this on the backend repo as well: https://github.com/RoyalBoroughKingston/ck-backend
