### ISSUE TITLE
Getting 404 response on PUT /collections/personas/:id

### ISSUE THREAD

**Issue by AyupMike** [RoyalBoroughKingston/ck-api#97]
**Describe the bug**
When trying to do a `PUT` request on the endpoint `/collections/personas/:id` i'm getting a 404 response.

**To Reproduce**
1. Use the endpoint `https://ck-api-staging.cloudapps.digital/core/v1/collections/personas/82b634a7-0415-4907-945d-68ce25816268`
2. Use the following request data
```
{
        "name": "People who are homeless (or at risk of)",
        "intro": "",
        "subtitle": "",
        "order": 1
}
```
3. Send a `PUT` request to the above endpoint using the request data

**Expected behavior**
I'd expect the entity to be updated and the endpoint to return a success response

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Mac OS High Sierra v10.13.6
 - Browser: Postman
 - Version 6.2.5

**Comment by matthew-inamdar** [comment]
Closing as the payload was missing the `category_taxonomies` field.

**Comment by AyupMike** [comment]
Perhaps we should be returning another HTTP status code if the request data is incorrect. `404` doesn't suggest that there is an issue with the request data, rather the resource/endpoint is not found/valid.

A might `400` make more sense - see [definition here](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.1)?

**Comment by matthew-inamdar** [comment]
Completely agree - I've created another issue to track this #116
